schema: "graphql/**/*.graphqls"
documents: "graphql/**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache
# schema: '**/*.graphqls'
# documents: '**/*.graphql'
# plugins:
#   - typescript-operations
#   - typescript-react-apollo
# cacheDir: .cache
