/* bd16bacedd6d00944942b4d02e6319485125f160
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
export declare type PartialFragment = ({
  __typename?: 'User';
} & Pick<Types.User, 'id' | 'username'>);
export declare const PartialFragmentDoc: import("@apollo/client").DocumentNode;